#!/bin/sh
#

# PROVIDE: dnsmon
# REQUIRE: NETWORKING SERVERS
# BEFORE:  DAEMON
# KEYWORD: shutdown

#
# Define these dnsmon_* variables in one of these files:
#       /etc/rc.conf
#       /etc/rc.conf.local
#
# dnsmon_enable="YES"		# Run the dnsmon daemon (YES/NO).
# dnsmon_flags=""		# Options
#
# DO NOT CHANGE THESE DEFAULT VALUES HERE
#
dnsmon_enable=${dnsmon_enable:-"NO"}
command_args="${dnsmon_flags:-""} --daemon"
command_interpreter="."

. /etc/rc.subr

name="dnsmon"
rcvar=dnsmon_enable


command="/usr/local/dnsmon/bin/dnsmon"
procname=$command

load_rc_config $name
run_rc_command "$1"

